name: Fetch Queue Times

on:
  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r queue-times-tracker-packages.txt

    - name: Run script
      run: |
        mkdir -p data
        python queue_time_tracker.py

    - name: Commit and push CSV
      run: |
        TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M")
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/
        git commit -m "Add queue times for $TIMESTAMP" || echo "No changes to commit"
        git push

# name: Fetch Queue Times

# on:
#   schedule:
#     - cron: '*/20 * * * *' # Runs every 20 minutes (UTC)
#   workflow_dispatch:        # Allows you to manually trigger it

# jobs:
#   fetch:
#     runs-on: ubuntu-latest 

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - name: Install dependencies
#       run: pip install -r queue-times-tracker-packages.txt

#     - name: Run script
#       run: python queue_time_tracker.py

#     - name: Upload CSV
#       uses: actions/upload-artifact@v4
#       with:
#         name: queue_times
#         path: queue_times.csv




# name: Fetch Queue Times

# on:
#   schedule:
#     - cron: '*/20 * * * *' # Runs every 20 minutes (UTC)
#   workflow_dispatch:        # Allows you to manually trigger it

# jobs:
#   fetch:
#     runs-on: ubuntu-latest 

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - name: Install dependencies
#       run: pip install -r queue-times-tracker-packages.txt

#     - name: Run script
#       run: python queue_time_tracker.py

#     - name: Set up GitHub token
#       run: |
#         echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

#     - name: Configure Git
#       run: |
#         git config --global user.name "github-actions[bot]"
#         git config --global user.email "github-actions[bot]@users.noreply.github.com"
#         git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.GH_TOKEN }}"

#     - name: Commit and push queue times CSV
#       run: |


#         git add data/queue_times.csv
#         git commit -m "Update queue times CSV"
#         git push origin main


# name: Fetch Queue Times

# on:
#   schedule:
#     - cron: '*/20 * * * *' # Runs every 20 minutes (UTC)
#   workflow_dispatch:        # Allows you to manually trigger it

# jobs:
#   fetch:
#     runs-on: ubuntu-latest 

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - name: Install dependencies
#       run: pip install -r queue-times-tracker-packages.txt

#     - name: Run script
#       run: python queue_time_tracker.py

#     - name: Configure Git
#       run: |
#         git config --global user.name "github-actions[bot]"
#         git config --global user.email "github-actions[bot]@users.noreply.github.com"

#     - name: Commit and push updated CSV
#       run: |
#         git add queue_times.csv
#         git commit -m "Append new queue times data"
#         git push origin main


