name: Fetch Queue Times

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:         

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r queue-times-tracker-packages.txt

    - name: Run script
      run: python queue_time_tracker.py

    - name: Commit and push CSV to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/queue_times.csv
        git commit -m "Update queue times CSV"
        git push origin main  # Replace with your branch if not 'main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# name: Fetch Queue Times

# on:
#   schedule:
#     - cron: '*/20 * * * *' # Runs every 20 minutes (UTC)
#   workflow_dispatch:        # Allows you to manually trigger it

# jobs:
#   fetch:
#     runs-on: ubuntu-latest 

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - name: Install dependencies
#       run: pip install -r queue-times-tracker-packages.txt

#     - name: Run script
#       run: python queue_time_tracker.py

#     - name: Upload CSV
#       uses: actions/upload-artifact@v4
#       with:
#         name: queue_times
#         path: queue_times.csv

